### ISSUE TITLE
Propagate warnings about unreadable files in mirror transfers

### ISSUE THREAD

**Issue by weaverba137** [desihub/desitransfer#17]
The Tucson mirror data transfers are turning up cases of unreadable files and directories.  These warnings should be passed on to the data management team, as well as being logged.  This may involve a refactor of logging for the mirror transfer.

**Comment by weaverba137** [comment]
PS, it would also be helpful to revisit the question of what is being mirrored, since these unreadable objects appear to be associated with ongoing analysis that is being written into areas that should be archival.

**Comment by sbailey** [comment]
Agreed about flagging unreadable files and directories so that we can quickly deal with them and not let them build up.

And also agreed about periodically revisiting what is mirrored and that ongoing analyses shouldn't be written to archival areas of the directory tree, but I think it can be valid for the mirror to include ongoing non-archival work (e.g. the daily reductions, or an in-progress working group analysis) as a backup for when NERSC is down or in the case of a catastrophic loss of CFS.  Some of these represent significant enough work that we don't want them to be unavailable during a NERSC outage, or completely lost if there is a disk crash prior to the analysis being done.
