### ISSUE TITLE
Alert experts for checksum failures

### ISSUE THREAD

**Issue by sbailey** [desihub/desitransfer#26]
To evaluate post-holidays:

Night 20201221 exposures 69213 and 69219 had their sky and focus files updated after the checksums were written as a side effect of testing/debugging at the time.  This of course shouldn't happen in normal operations, but how should we handle it when cases like this do happen?

For 69213 this resulted in a checksum failure message in the desitransfer logs.  Suggested action: checksum failures should generate desi-alarms-transfer emails or other alerts so that experts can followup on why the checksums failed.  I noticed this case because nightwatch at KPNO had this exposure but nightwatch at NERSC did not.

For 69219 it was transferred with good checksums *before* the sky and focus files were updated and thus didn't generate a checksum failure in the middle of the night, and resulting in KPNO and NERSC having different versions of the sky and focus files during the night.  It appears that the morning cleanup pass resynced the updated files from KPNO but I don't see any mention of that in the desi/spectro/staging/logs/desi_transfer_daemon.log so I'm not sure where the morning sync logs go.  Regardless, this also seems like a situation that should generate a louder alert to experts for followup (on the ICS side to prevent bad checksums in the first place, and the on spectro pipeline side because it might require some cleanup, i.e. not just desitransfer experts).

**Comment by weaverba137** [comment]
> 20201221/00069213

From the description, is this a case where there were *extra* files as described in #25?  In other words, do you want the procedure suggested in #25 to also be applied in this case?  In other words, would you have wanted this exposure moved to `$DESI_SPECTRO_DATA` anyway?

> 20201221/00069219

The low-level catch-up log is written to `$SCRATCH` and then parsed for errors. However, only `rsync` errors are detected, and only that is what is reported to `desi_transfer_daemon.log`.

The checksum files are *not* re-checked as part of this stage.  At the time the catch-ups were implemented, we were not getting ICS checksums *at all* so it was assumed that any checksum files would be generated after the fact and would not need to be recomputed.

In order to generate an alert then we would have to go back and recompute the checksum, possibly first eliminating exposures that did not change during the catch-up phase.
